### ISSUE TITLE
Тест некорректно проверяет блокировку GA и метрики

### ISSUE THREAD

**Issue by ameshkov** [whitematchmarketing/adblock-tester#1]
В случае всех блокировщиков скрипт сбоит на этой проверке.

Проще было бы проверять вот так:
```
var checkScriptLoad = function(url, callback) {

    var script = document.createElement('script');
    script.setAttribute('src', url);
    script.setAttribute('async', true);
    script.onload = function() {
        script.parentNode.removeChild(script);
        callback(true);
    };
    script.onerror = function() {
        script.parentNode.removeChild(script);
        callback(false);
    };
    document.head.appendChild(script);
};

checkScriptLoad('https://www.google-analytics.com/analytics.js', function(result) {
    updateRez(document.querySelector('.js-ga'), result);
});

checkScriptLoad('https://mc.yandex.ru/metrika/watch.js', function(result) {
    // TODO: update yandex element
});
```

**Comment by ministr91** [comment]
не починили

**Comment by ymatuhin** [comment]
@ameshkov Извините, я пропустил ваше сообщение, в принципе вы абсолютно правы. Это дало бы ответ на то, блокирует ли загрузку скрипта. Но я переживал что возможно блокировщики будут как-то подменять его или вырезать скрипт прямо из html. Ведь в скрипте яндекс-метрики так-же есть картинка на https://mc.yandex.ru/watch/43211979.
Сейчас проверяются переменные `inited`, которые проставляются в true скриптами счетчиков.

**Comment by ameshkov** [comment]
@ymatuhin 
> Но я переживал что возможно блокировщики будут как-то подменять его или вырезать скрипт прямо из html

Ну кстати это обосновано, некоторые (например AG) действительно могут вырезать тег `<script>`, который указывает на заблокированный ресурс.

Поэтому я и предлагаю динамически добавлять эти скрипты на страницу, в этом случае они будут его видеть при загрузке страницы.

**Comment by ameshkov** [comment]
Вроде все ок теперь работает, спасибо!
