### ISSUE TITLE
Дополнение к предыдущей проблеме

### ISSUE THREAD

**Issue by ministr91** [whitematchmarketing/adblock-tester#2]
Ранее п.6 теста (Гугл аналитика) проверял способность блокировщика работать с правилами блокировки скриптов. В частности, этот пункт срабатывал на правило 
||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js

Затем, по жалобе, на котором этот пункт не срабатывал, тест-сайт был изменен. 

Теперь этот пункт срабатывает по хостс-списку!!! Чего не должно быть в принципе - хостс-списки не содержат правил блокировки вообще! 

Если, конечно, мы проверяем способность блокировщика работать с правилами блокировки скриптов, а не получение красивой картинки.

Фактически, сейчас имеем дублирование п.1 теста (который проверяет блокировку загрузки рекламы с рекламных доменов, т.е. работу блокировщиков по хостс-спискам) и потерю 1/6 функционала.

**Comment by ymatuhin** [comment]
Как я понимаю, если адрес гугл-аналитики есть в хостс списке и перенаправляет на локалхост, то гугл аналитика не будет доступна и не должна быть. Можете ли вы переформулировать как-то ваш вопрос? Мне не понятно в чем проблема и чем я могу помочь.

**Comment by ministr91** [comment]
@ymatuhin 
Не стоило заявлять, что сайт тестирует блокировщики. П.к.м. я понял так, что проверяются их технические возможности. На самом же деле - просто наличие определенных фильтров.

Например, пункты 1, 5, 6 (сейчас) срабатывают на блокировку трех известных хостов, которые давным-давно вбиты во все нормальные хостс-списки. Что тут проверять?

Оставшиеся баннеры отключаются обычными косметическими правилами (фактически, одним правилом). Макс. две подписки перебрал - и найдутся необходимые для этого случая. Для других случаев - будут нужны другие.
В общем - тест ни о чем.

**Comment by ymatuhin** [comment]
Проверка идет для пользователей, видят ли они рекламу и загрузилась ли аналика с сайта которая для пользователя не важна. Не вижу смысла в дальнейшем обсуждении.
